name: DVC Tracking with Github Actions
on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Running_updates
        run: |
          pip install -r requirements.txt
          dvc repro
          git fetch --prune
          dvc metrics diff main
