# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: DVC application

on:
  push:
    branches: [ "i200802" ]
  pull_request:
    branches: [ "i200802" ]
    
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Running_updates
        run: |
          pip install -r requirements.txt
          dvc repro
          git fetch --prune
          dvc metrics diff main
